version: '3.0'

services:
  rasa:
    # image: rasa/rasa:2.8.5-full
    image: tabot/ch-rasa:v0.1
    container_name: tabot-rasa-ch
  #  restart: always
    networks: ['tabot']
    user: root
    ports:
      - "5005:5005"
    volumes:
      - "./:/app/"
    depends_on:
      - action_server
    command:
      - run
      - --model
      - /app/models/tabot-ch.tar.gz
      - --endpoints
      - /app/endpoints.yml
      - -vv
      - --enable-api

  action_server:
    image: tabot/ch-rasa-action:v0.1
    container_name: tabot-rasa-action
#    restart: always
    networks: ['tabot']
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/bot/actions"
    command:
      - start
      - --actions
      - actions
      - -vv

# networks: {rasa-network: {}}
networks:
  tabot:
    name: tabot