version: '3.0'

services:
  tabot-rasa-ch:
    # image: rasa/rasa:2.8.5-full
    image: tabot/rasa-ch:v0.1
    container_name: tabot-rasa-ch
    restart: always
    networks: ['tabot']
    user: root
    ports:
      - "15005:5005"
    volumes:
      - "./ch/:/app/"
    depends_on:
      - tabot-rasa-action
    command:
      - run 
      - --model 
      - /app/models/tabot-ch.tar.gz 
      - --endpoints 
      - /app/endpoints.yml 
      - -vv 
      - --enable-api
  
  tabot-rasa-en:
    image: rasa/rasa:3.2.6-full
    container_name: tabot-rasa-en
    restart: always
    networks: ['tabot']
    user: root
    ports:
      - "15006:5005"
    volumes:
      - "./en/:/app/"
    depends_on:
      - tabot-rasa-action
    command:
      - run 
      - --model 
      - /app/models/tabot-en.tar.gz 
      - --endpoints 
      - /app/endpoints.yml 
      - -vv 
      - --enable-api

  tabot-rasa-action:
    image: tabot/rasa-ch-action:v0.1
    container_name: tabot-rasa-action
    restart: always
    networks: ['tabot']
    ports:
      - "15055:5055"
    volumes:
      - "./actions:/bot/actions"
    command:
      - start
      - --actions
      - actions
      - -vv

# networks: {rasa-network: {}}
networks:
  tabot:
    name: tabot