version: '3.0'

services:
  rasa-zh:
    # image: rasa/rasa:2.8.5-full
    image: tabot/ch-rasa:v0.1
    container_name: tabot-rasa-ch
    restart: always
    networks: ['rasa-network']
    user: root
    ports:
      - "5005:5005"
    volumes:
      - "./ch/:/app/"
    depends_on:
      - action_server
    command:
      - run
      - --model
      - /app/models/tabot-ch.tar.gz
      - --endpoints
      - /app/endpoints.yml
      - -vv
      - --enable-api
  
  rasa-en:
    image: rasa/rasa:2.8.5-full
    container_name: tabot-rasa-en
    restart: always
    networks: ['rasa-network']
    user: root
    ports:
      - "5006:5005"
    volumes:
      - "./en/:/app/"
    depends_on:
      - action_server
    command:
      - run
      - --model
      - /app/models/tabot-en.tar.gz
      - --endpoints
      - /app/endpoints.yml
      - -vv
      - --enable-api

  action_server:
    image: tabot/ch-action:v0.1
    container_name: tabot-action
    restart: always
    networks: ['rasa-network']
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/bot/actions"
    command:
      - start
      - --actions
      - actions
      - -vv

# networks: {rasa-network: {}}
networks:
  tabot:
    name: tabot